'use server'

import { revalidatePath } from 'next/cache'
import { requireUser } from '@/lib/actions/auth'

/**
 * Dismiss the technician first-login welcome card on the current tenant.
 *
 * Stamps `tenant_members.tech_onboarded_at` = now() for the current
 * (user_id, tenant_id) pair. After this the TechDashboard stops
 * rendering the welcome surface — see PR I in the UX audit PR slicing.
 *
 * Idempotent — re-calling on an already-stamped row is a no-op (the
 * timestamp moves forward but the UI doesn't care).
 */
export async function dismissTechWelcomeAction() {
  try {
    const { supabase, tenantId, user } = await requireUser()

    // Cast to bypass autogenerated database.types.ts which hasn't picked
    // up the new tech_onboarded_at column from migration 0102 yet.
    // Regenerating types is a separate ops step.
    const { error } = await supabase
      .from('tenant_members')
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      .update({ tech_onboarded_at: new Date().toISOString() } as any)
      .eq('user_id', user.id)
      .eq('tenant_id', tenantId)

    if (error) return { success: false as const, error: error.message }

    revalidatePath('/dashboard')
    return { success: true as const }
  } catch (e: unknown) {
    return { success: false as const, error: (e as Error).message }
  }
}
