// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/settings" | "/admin/users" | "/assets" | "/auth/enroll-mfa" | "/auth/forgot-password" | "/auth/mfa" | "/auth/reset-password" | "/auth/signin" | "/customers" | "/dashboard" | "/job-plans" | "/maintenance" | "/reports" | "/settings" | "/sites" | "/testing"
type AppRouteHandlerRoutes = "/api/assets" | "/api/assets/[id]" | "/api/customers" | "/api/customers/[id]" | "/api/health" | "/api/job-plans" | "/api/job-plans/[id]" | "/api/job-plans/[id]/items" | "/api/job-plans/[id]/items/[itemId]" | "/api/sites" | "/api/sites/[id]" | "/api/tenants" | "/api/tenants/[id]" | "/auth/callback" | "/auth/signout"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin/settings": {}
  "/admin/users": {}
  "/api/assets": {}
  "/api/assets/[id]": { "id": string; }
  "/api/customers": {}
  "/api/customers/[id]": { "id": string; }
  "/api/health": {}
  "/api/job-plans": {}
  "/api/job-plans/[id]": { "id": string; }
  "/api/job-plans/[id]/items": { "id": string; }
  "/api/job-plans/[id]/items/[itemId]": { "id": string; "itemId": string; }
  "/api/sites": {}
  "/api/sites/[id]": { "id": string; }
  "/api/tenants": {}
  "/api/tenants/[id]": { "id": string; }
  "/assets": {}
  "/auth/callback": {}
  "/auth/enroll-mfa": {}
  "/auth/forgot-password": {}
  "/auth/mfa": {}
  "/auth/reset-password": {}
  "/auth/signin": {}
  "/auth/signout": {}
  "/customers": {}
  "/dashboard": {}
  "/job-plans": {}
  "/maintenance": {}
  "/reports": {}
  "/settings": {}
  "/sites": {}
  "/testing": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
