-- ============================================================
-- Migration: 0004_test_records_schema
-- Sprint 8 — Test Records per Asset
-- Applied to: urjhmkhbgaxrofurpbgc (eq-solves-service-dev)
-- ============================================================

-- See full SQL in the apply_migration call for Sprint 8.
-- Tables: test_records, test_record_readings
-- RLS: tenant-scoped, supervisor+ write, admin delete
-- Indexes on tenant, asset, site, result, dates
-- updated_at triggers via set_updated_at()
